name: Build and Test VB.NET Framework Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # 1. Repository auschecken
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. MSBuild verwenden, um das Projekt zu bauen
    - name: Build Project
      run: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\MSBuild.exe Autodatenbank3.sln /p:Configuration=Release"

    # 3. Optional: Tests ausführen, falls vorhanden
    - name: Run Unit Tests
      run: vstest.console.exe Autodatenbank.Tests.dll /Platform:x64
