name: Build and Test VB.NET Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # 1. Repository auschecken
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. .NET SDK einrichten
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.8 

    # 3. Abhängigkeiten wiederherstellen
    - name: Restore dependencies
      run: dotnet restore YourVBProject.sln

    # 4. Projekt bauen
    - name: Build VB.NET Project
      run: dotnet build YourVBProject.sln --configuration Release

    # 5. Tests ausführen
    - name: Run VB.NET Tests
      run: dotnet test YourVBProject.sln --no-build --verbosity normal
